<?php
declare(strict_types=1);

// MullvadVpn SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MullvadVpnUtility::setRegistrar(function (MullvadVpnUtility $u): void {
    $u->clean = [MullvadVpnClean::class, 'call'];
    $u->done = [MullvadVpnDone::class, 'call'];
    $u->make_error = [MullvadVpnMakeError::class, 'call'];
    $u->feature_add = [MullvadVpnFeatureAdd::class, 'call'];
    $u->feature_hook = [MullvadVpnFeatureHook::class, 'call'];
    $u->feature_init = [MullvadVpnFeatureInit::class, 'call'];
    $u->fetcher = [MullvadVpnFetcher::class, 'call'];
    $u->make_fetch_def = [MullvadVpnMakeFetchDef::class, 'call'];
    $u->make_context = [MullvadVpnMakeContext::class, 'call'];
    $u->make_options = [MullvadVpnMakeOptions::class, 'call'];
    $u->make_request = [MullvadVpnMakeRequest::class, 'call'];
    $u->make_response = [MullvadVpnMakeResponse::class, 'call'];
    $u->make_result = [MullvadVpnMakeResult::class, 'call'];
    $u->make_point = [MullvadVpnMakePoint::class, 'call'];
    $u->make_spec = [MullvadVpnMakeSpec::class, 'call'];
    $u->make_url = [MullvadVpnMakeUrl::class, 'call'];
    $u->param = [MullvadVpnParam::class, 'call'];
    $u->prepare_auth = [MullvadVpnPrepareAuth::class, 'call'];
    $u->prepare_body = [MullvadVpnPrepareBody::class, 'call'];
    $u->prepare_headers = [MullvadVpnPrepareHeaders::class, 'call'];
    $u->prepare_method = [MullvadVpnPrepareMethod::class, 'call'];
    $u->prepare_params = [MullvadVpnPrepareParams::class, 'call'];
    $u->prepare_path = [MullvadVpnPreparePath::class, 'call'];
    $u->prepare_query = [MullvadVpnPrepareQuery::class, 'call'];
    $u->graphql_body = [MullvadVpnGraphql::class, 'body'];
    $u->graphql_errors = [MullvadVpnGraphql::class, 'errors'];
    $u->result_basic = [MullvadVpnResultBasic::class, 'call'];
    $u->result_body = [MullvadVpnResultBody::class, 'call'];
    $u->result_headers = [MullvadVpnResultHeaders::class, 'call'];
    $u->transform_request = [MullvadVpnTransformRequest::class, 'call'];
    $u->transform_response = [MullvadVpnTransformResponse::class, 'call'];
});
